import type { CategoryCatalogEntry } from "./schema";

export const categories = [
  {
    key: "banner",
    name: "banner",
    title: "Banner",
    blockOrder: 27,
  },
  {
    key: "carousel",
    name: "carousel",
    title: "Carousel",
    blockOrder: 16,
  },
  {
    key: "changelog",
    name: "changelog",
    title: "Changelog",
    blockOrder: 17,
  },
  {
    key: "codeBlock",
    name: "codeBlock",
    title: "Code Block",
    blockOrder: 18,
  },
  {
    key: "emptyState",
    name: "emptyState",
    title: "Empty State",
    blockOrder: 19,
  },
  {
    key: "inviteMember",
    name: "inviteMember",
    title: "Invite Member",
    blockOrder: 20,
  },
  {
    key: "keyboardShortcuts",
    name: "keyboardShortcuts",
    title: "Keyboard Shortcuts",
    blockOrder: 21,
  },
  {
    key: "members",
    name: "members",
    title: "Members",
    blockOrder: 22,
  },
  {
    key: "orderConfirmation",
    name: "orderConfirmation",
    title: "Order Confirmation",
    blockOrder: 23,
  },
  {
    key: "profile",
    name: "profile",
    title: "Profile",
    blockOrder: 24,
  },
  {
    key: "cta",
    name: "cta",
    title: "CTA",
    blockOrder: 5,
  },
  {
    key: "setupGuide",
    name: "setupGuide",
    title: "Setup Guide",
    blockOrder: 25,
  },
  {
    key: "integrations",
    name: "integrations",
    title: "Integrations",
    blockOrder: 2,
  },
  {
    key: "verification",
    name: "verification",
    title: "Verification",
    blockOrder: 26,
  },
  {
    key: "logoCloud",
    name: "logoCloud",
    title: "Logo Cloud",
    blockOrder: 12,
  },
  {
    key: "testimonials",
    name: "testimonials",
    title: "Testimonials",
    blockOrder: 7,
  },
  {
    key: "signup",
    name: "signup",
    title: "Signup",
    blockOrder: 9,
  },
  {
    key: "hero",
    name: "hero",
    title: "Hero",
    blockOrder: 0,
  },
  {
    key: "faq",
    name: "faq",
    title: "FAQ",
    blockOrder: 6,
  },
  {
    key: "pricing",
    name: "pricing",
    title: "Pricing",
    blockOrder: 4,
  },
  {
    key: "features",
    name: "features",
    title: "Features",
    blockOrder: 1,
  },
  {
    key: "team",
    name: "team",
    title: "Team",
    blockOrder: 3,
  },
  {
    key: "stats",
    name: "stats",
    title: "Stats",
    blockOrder: 13,
  },
  {
    key: "footer",
    name: "footer",
    title: "Footer",
    blockOrder: 11,
  },
  {
    key: "contact",
    name: "contact",
    title: "Contact",
    blockOrder: 14,
  },
  {
    key: "navbar",
    name: "navbar",
    title: "Navbar",
    blockOrder: 10,
  },
  {
    key: "login",
    name: "login",
    title: "Login",
    blockOrder: 8,
  },
  {
    key: "authentication",
    name: "authentication",
    title: "Authentication",
  },
  {
    key: "timeline",
    name: "timeline",
    title: "Timeline",
    blockOrder: 15,
  },
  {
    key: "blog",
    name: "blog",
    title: "Blog",
    blockOrder: 28,
  },
  {
    key: "notFound",
    name: "notFound",
    title: "Not Found",
    blockOrder: 29,
  },
] as const satisfies readonly CategoryCatalogEntry[];
