/**
 * Maps Lucide icon names to their equivalents across icon libraries.
 * Used by IconPlaceholder to render the correct icon when user selects a different icon library.
 *
 * Naming conventions:
 * - Lucide: PascalCase, sometimes with Icon suffix (e.g. ChevronDown, CheckIcon)
 * - Tabler: Icon prefix (e.g. IconChevronDown, IconCheck)
 * - Hugeicons: PascalCase with Icon suffix (e.g. ArrowDown01Icon, Tick02Icon)
 * - Phosphor: PascalCase with Icon suffix (e.g. CaretDownIcon, CheckIcon)
 * - RemixIcon: Ri prefix + PascalCase + Line/Fill (e.g. RiArrowDownSLine, RiCheckLine)
 */
export const ICON_MAP: Record<
  string,
  {
    lucide: string;
    tabler: string;
    hugeicons: string;
    phosphor: string;
    remixicon: string;
  }
> = {
  // Arrows & navigation
  ArrowRight: {
    lucide: "ArrowRight",
    tabler: "IconArrowRight",
    hugeicons: "ArrowRight01Icon",
    phosphor: "ArrowRight",
    remixicon: "RiArrowRightLine",
  },
  ArrowUpRight: {
    lucide: "ArrowUpRight",
    tabler: "IconArrowUpRight",
    hugeicons: "ArrowUpRight01Icon",
    phosphor: "ArrowUpRight",
    remixicon: "RiArrowUpRightLine",
  },
  ArrowUpDown: {
    lucide: "ArrowUpDown",
    tabler: "IconArrowsSort",
    hugeicons: "ArrowUpDown01Icon",
    phosphor: "ArrowsDownUp",
    remixicon: "RiArrowUpDownLine",
  },
  ChevronDown: {
    lucide: "ChevronDown",
    tabler: "IconChevronDown",
    hugeicons: "ArrowDown01Icon",
    phosphor: "CaretDown",
    remixicon: "RiArrowDownSLine",
  },
  ChevronUp: {
    lucide: "ChevronUp",
    tabler: "IconChevronUp",
    hugeicons: "ArrowUp01Icon",
    phosphor: "CaretUp",
    remixicon: "RiArrowUpSLine",
  },
  ChevronLeft: {
    lucide: "ChevronLeft",
    tabler: "IconChevronLeft",
    hugeicons: "ArrowLeft01Icon",
    phosphor: "CaretLeft",
    remixicon: "RiArrowLeftSLine",
  },
  ChevronRight: {
    lucide: "ChevronRight",
    tabler: "IconChevronRight",
    hugeicons: "ArrowRight01Icon",
    phosphor: "CaretRight",
    remixicon: "RiArrowRightSLine",
  },
  ChevronLeftIcon: {
    lucide: "ChevronLeftIcon",
    tabler: "IconChevronLeft",
    hugeicons: "ArrowLeft01Icon",
    phosphor: "CaretLeft",
    remixicon: "RiArrowLeftSLine",
  },
  ChevronRightIcon: {
    lucide: "ChevronRightIcon",
    tabler: "IconChevronRight",
    hugeicons: "ArrowRight01Icon",
    phosphor: "CaretRight",
    remixicon: "RiArrowRightSLine",
  },
  ChevronsRight: {
    lucide: "ChevronsRight",
    tabler: "IconChevronsRight",
    hugeicons: "ArrowRight02Icon",
    phosphor: "CaretDoubleRight",
    remixicon: "RiArrowRightDoubleLine",
  },
  ChevronsLeft: {
    lucide: "ChevronsLeft",
    tabler: "IconChevronsLeft",
    hugeicons: "ArrowLeft02Icon",
    phosphor: "CaretDoubleLeft",
    remixicon: "RiArrowLeftDoubleLine",
  },
  ChevronsUpDown: {
    lucide: "ChevronsUpDown",
    tabler: "IconSelector",
    hugeicons: "UnfoldMoreIcon",
    phosphor: "CaretUpDown",
    remixicon: "RiArrowUpDownLine",
  },
  ChevronsUp: {
    lucide: "ChevronsUp",
    tabler: "IconChevronsUp",
    hugeicons: "ArrowUp02Icon",
    phosphor: "CaretDoubleUp",
    remixicon: "RiArrowUpDoubleLine",
  },
  ChevronFirst: {
    lucide: "ChevronFirst",
    tabler: "IconPlayerSkipBack",
    hugeicons: "SkipBackIcon",
    phosphor: "SkipBack",
    remixicon: "RiSkipBackLine",
  },
  ChevronLast: {
    lucide: "ChevronLast",
    tabler: "IconPlayerSkipForward",
    hugeicons: "SkipForwardIcon",
    phosphor: "SkipForward",
    remixicon: "RiSkipForwardLine",
  },

  // Actions & UI
  Check: {
    lucide: "Check",
    tabler: "IconCheck",
    hugeicons: "Tick02Icon",
    phosphor: "Check",
    remixicon: "RiCheckLine",
  },
  CheckIcon: {
    lucide: "CheckIcon",
    tabler: "IconCheck",
    hugeicons: "Tick02Icon",
    phosphor: "Check",
    remixicon: "RiCheckLine",
  },
  X: {
    lucide: "X",
    tabler: "IconX",
    hugeicons: "Cancel01Icon",
    phosphor: "X",
    remixicon: "RiCloseLine",
  },
  XIcon: {
    lucide: "XIcon",
    tabler: "IconX",
    hugeicons: "Cancel01Icon",
    phosphor: "X",
    remixicon: "RiCloseLine",
  },
  XCircleIcon: {
    lucide: "XCircleIcon",
    tabler: "IconCircleX",
    hugeicons: "MultiplicationSignCircleIcon",
    phosphor: "XCircle",
    remixicon: "RiCloseCircleLine",
  },
  Plus: {
    lucide: "Plus",
    tabler: "IconPlus",
    hugeicons: "Add01Icon",
    phosphor: "Plus",
    remixicon: "RiAddLine",
  },
  Copy: {
    lucide: "Copy",
    tabler: "IconCopy",
    hugeicons: "Copy01Icon",
    phosphor: "Copy",
    remixicon: "RiFileCopyLine",
  },
  MoreHorizontal: {
    lucide: "MoreHorizontal",
    tabler: "IconDots",
    hugeicons: "MoreHorizontalCircle01Icon",
    phosphor: "DotsThree",
    remixicon: "RiMoreLine",
  },
  MoreHorizontalIcon: {
    lucide: "MoreHorizontalIcon",
    tabler: "IconDots",
    hugeicons: "MoreHorizontalCircle01Icon",
    phosphor: "DotsThree",
    remixicon: "RiMoreLine",
  },
  SearchIcon: {
    lucide: "SearchIcon",
    tabler: "IconSearch",
    hugeicons: "SearchIcon",
    phosphor: "MagnifyingGlass",
    remixicon: "RiSearchLine",
  },
  RefreshCcw: {
    lucide: "RefreshCcw",
    tabler: "IconRefresh",
    hugeicons: "RefreshIcon",
    phosphor: "ArrowClockwise",
    remixicon: "RiRefreshLine",
  },
  Columns3: {
    lucide: "Columns3",
    tabler: "IconLayoutColumns",
    hugeicons: "Columns03Icon",
    phosphor: "Columns",
    remixicon: "RiLayoutColumnLine",
  },
  Rows2: {
    lucide: "Rows2",
    tabler: "IconLayoutRows",
    hugeicons: "Rows02Icon",
    phosphor: "Rows",
    remixicon: "RiLayoutRowLine",
  },
  Rows3: {
    lucide: "Rows3",
    tabler: "IconLayoutRows",
    hugeicons: "Rows03Icon",
    phosphor: "Rows",
    remixicon: "RiLayoutRowLine",
  },
  Rows4: {
    lucide: "Rows4",
    tabler: "IconLayoutRows",
    hugeicons: "Rows04Icon",
    phosphor: "Rows",
    remixicon: "RiLayoutRowLine",
  },
  Equal: {
    lucide: "Equal",
    tabler: "IconEqual",
    hugeicons: "EqualIcon",
    phosphor: "Equals",
    remixicon: "RiEqualLine",
  },
  Ellipsis: {
    lucide: "Ellipsis",
    tabler: "IconDots",
    hugeicons: "MoreHorizontalCircle01Icon",
    phosphor: "DotsThree",
    remixicon: "RiMoreLine",
  },
  EllipsisVertical: {
    lucide: "EllipsisVertical",
    tabler: "IconDotsVertical",
    hugeicons: "MoreVerticalCircle01Icon",
    phosphor: "DotsThreeVertical",
    remixicon: "RiMore2Line",
  },

  // Status & alerts
  AlertTriangleIcon: {
    lucide: "AlertTriangleIcon",
    tabler: "IconAlertTriangle",
    hugeicons: "Alert02Icon",
    phosphor: "Warning",
    remixicon: "RiErrorWarningLine",
  },
  OctagonAlert: {
    lucide: "OctagonAlert",
    tabler: "IconAlertOctagon",
    hugeicons: "MultiplicationSignCircleIcon",
    phosphor: "WarningOctagon",
    remixicon: "RiErrorWarningLine",
  },
  InfoIcon: {
    lucide: "InfoIcon",
    tabler: "IconInfoCircle",
    hugeicons: "InformationCircleIcon",
    phosphor: "Info",
    remixicon: "RiInformationLine",
  },
  CircleCheckBigIcon: {
    lucide: "CircleCheckBigIcon",
    tabler: "IconCircleCheck",
    hugeicons: "CheckmarkCircle02Icon",
    phosphor: "CheckCircle",
    remixicon: "RiCheckboxCircleLine",
  },
  CircleFadingArrowUp: {
    lucide: "CircleFadingArrowUp",
    tabler: "IconArrowUpCircle",
    hugeicons: "ArrowUpCircleIcon",
    phosphor: "ArrowCircleUp",
    remixicon: "RiArrowUpCircleLine",
  },
  CircleFadingArrowUpIcon: {
    lucide: "CircleFadingArrowUpIcon",
    tabler: "IconArrowUpCircle",
    hugeicons: "ArrowUpCircleIcon",
    phosphor: "ArrowCircleUp",
    remixicon: "RiArrowUpCircleLine",
  },
  ShieldAlert: {
    lucide: "ShieldAlert",
    tabler: "IconShieldExclamation",
    hugeicons: "ShieldSecurityIcon",
    phosphor: "ShieldWarning",
    remixicon: "RiShieldAlertLine",
  },
  OctagonAlertIcon: {
    lucide: "OctagonAlertIcon",
    tabler: "IconAlertOctagon",
    hugeicons: "MultiplicationSignCircleIcon",
    phosphor: "WarningOctagon",
    remixicon: "RiErrorWarningLine",
  },

  // Media & content
  Star: {
    lucide: "Star",
    tabler: "IconStar",
    hugeicons: "Star01Icon",
    phosphor: "Star",
    remixicon: "RiStarLine",
  },
  StarIcon: {
    lucide: "StarIcon",
    tabler: "IconStar",
    hugeicons: "Star01Icon",
    phosphor: "Star",
    remixicon: "RiStarLine",
  },
  Heart: {
    lucide: "Heart",
    tabler: "IconHeart",
    hugeicons: "Heart01Icon",
    phosphor: "Heart",
    remixicon: "RiHeartLine",
  },
  HeartIcon: {
    lucide: "HeartIcon",
    tabler: "IconHeart",
    hugeicons: "Heart01Icon",
    phosphor: "Heart",
    remixicon: "RiHeartLine",
  },
  BookmarkIcon: {
    lucide: "BookmarkIcon",
    tabler: "IconBookmark",
    hugeicons: "Bookmark01Icon",
    phosphor: "Bookmark",
    remixicon: "RiBookmarkLine",
  },
  CircleCheck: {
    lucide: "CircleCheck",
    tabler: "IconCircleCheck",
    hugeicons: "CheckmarkCircle02Icon",
    phosphor: "CheckCircle",
    remixicon: "RiCheckboxCircleLine",
  },
  CircleHelpIcon: {
    lucide: "CircleHelpIcon",
    tabler: "IconHelpCircle",
    hugeicons: "HelpCircleIcon",
    phosphor: "Question",
    remixicon: "RiQuestionLine",
  },
  CirclePlay: {
    lucide: "CirclePlay",
    tabler: "IconPlayerPlay",
    hugeicons: "PlayCircleIcon",
    phosphor: "PlayCircle",
    remixicon: "RiPlayCircleLine",
  },
  FlaskConicalIcon: {
    lucide: "FlaskConicalIcon",
    tabler: "IconFlask",
    hugeicons: "FlaskIcon",
    phosphor: "Flask",
    remixicon: "RiFlaskLine",
  },
  SparklesIcon: {
    lucide: "SparklesIcon",
    tabler: "IconSparkles",
    hugeicons: "Sparkles01Icon",
    phosphor: "Sparkle",
    remixicon: "RiSparklingLine",
  },
  Code: {
    lucide: "Code",
    tabler: "IconCode",
    hugeicons: "Code01Icon",
    phosphor: "Code",
    remixicon: "RiCodeLine",
  },
  Rocket: {
    lucide: "Rocket",
    tabler: "IconRocket",
    hugeicons: "Rocket01Icon",
    phosphor: "RocketLaunch",
    remixicon: "RiRocketLine",
  },
  Trash: {
    lucide: "Trash",
    tabler: "IconTrash",
    hugeicons: "Delete02Icon",
    phosphor: "Trash",
    remixicon: "RiDeleteBinLine",
  },
  ExternalLink: {
    lucide: "ExternalLink",
    tabler: "IconExternalLink",
    hugeicons: "LinkSquare02Icon",
    phosphor: "ArrowSquareOut",
    remixicon: "RiExternalLinkLine",
  },
  ImageIcon: {
    lucide: "ImageIcon",
    tabler: "IconPhoto",
    hugeicons: "Image01Icon",
    phosphor: "Image",
    remixicon: "RiImageLine",
  },
  MessageCircleIcon: {
    lucide: "MessageCircleIcon",
    tabler: "IconMessageCircle",
    hugeicons: "MessageCircleIcon",
    phosphor: "ChatCircle",
    remixicon: "RiChat3Line",
  },
  ShareIcon: {
    lucide: "ShareIcon",
    tabler: "IconShare",
    hugeicons: "Share01Icon",
    phosphor: "ShareNetwork",
    remixicon: "RiShareLine",
  },

  // User & profile
  User: {
    lucide: "User",
    tabler: "IconUser",
    hugeicons: "User01Icon",
    phosphor: "User",
    remixicon: "RiUserLine",
  },
  UserRoundIcon: {
    lucide: "UserRoundIcon",
    tabler: "IconUserCircle",
    hugeicons: "UserCircleIcon",
    phosphor: "UserCircle",
    remixicon: "RiUserLine",
  },
  BuildingIcon: {
    lucide: "BuildingIcon",
    tabler: "IconBuilding",
    hugeicons: "Building01Icon",
    phosphor: "Buildings",
    remixicon: "RiBuildingLine",
  },
  StoreIcon: {
    lucide: "StoreIcon",
    tabler: "IconBuildingStore",
    hugeicons: "Store01Icon",
    phosphor: "Storefront",
    remixicon: "RiStoreLine",
  },
  BadgeCheckIcon: {
    lucide: "BadgeCheckIcon",
    tabler: "IconBadgeCheck",
    hugeicons: "BadgeCheckIcon",
    phosphor: "IdentificationBadge",
    remixicon: "RiShieldCheckLine",
  },
  BadgeCheck: {
    lucide: "BadgeCheck",
    tabler: "IconBadgeCheck",
    hugeicons: "BadgeCheckIcon",
    phosphor: "IdentificationBadge",
    remixicon: "RiShieldCheckLine",
  },
  BadgeMinus: {
    lucide: "BadgeMinus",
    tabler: "IconBadgeMinus",
    hugeicons: "BadgeMinusIcon",
    phosphor: "IdentificationBadge",
    remixicon: "RiShieldLine",
  },
  BadgeX: {
    lucide: "BadgeX",
    tabler: "IconBadgeX",
    hugeicons: "BadgeXIcon",
    phosphor: "IdentificationBadge",
    remixicon: "RiShieldCrossLine",
  },
  Settings: {
    lucide: "Settings",
    tabler: "IconSettings",
    hugeicons: "Settings01Icon",
    phosphor: "Gear",
    remixicon: "RiSettingsLine",
  },
  Settings2: {
    lucide: "Settings2",
    tabler: "IconSettings",
    hugeicons: "Settings02Icon",
    phosphor: "Gear",
    remixicon: "RiSettings3Line",
  },
  LogOut: {
    lucide: "LogOut",
    tabler: "IconLogout",
    hugeicons: "Logout01Icon",
    phosphor: "SignOut",
    remixicon: "RiLogoutBoxLine",
  },
  Eye: {
    lucide: "Eye",
    tabler: "IconEye",
    hugeicons: "ViewIcon",
    phosphor: "Eye",
    remixicon: "RiEyeLine",
  },

  // Navigation & layout
  Home: {
    lucide: "Home",
    tabler: "IconHome",
    hugeicons: "Home01Icon",
    phosphor: "House",
    remixicon: "RiHomeLine",
  },
  Component: {
    lucide: "Component",
    tabler: "IconComponents",
    hugeicons: "ComponentIcon",
    phosphor: "SquaresFour",
    remixicon: "RiLayoutGridLine",
  },
  Route: {
    lucide: "Route",
    tabler: "IconRoute",
    hugeicons: "RouteIcon",
    phosphor: "MapTrifold",
    remixicon: "RiRouteLine",
  },
  Slash: {
    lucide: "Slash",
    tabler: "IconSlash",
    hugeicons: "SlashIcon",
    phosphor: "Slash",
    remixicon: "RiSlashLine",
  },
  Dot: {
    lucide: "Dot",
    tabler: "IconPoint",
    hugeicons: "DotIcon",
    phosphor: "Circle",
    remixicon: "RiRecordCircleLine",
  },
  BookOpen: {
    lucide: "BookOpen",
    tabler: "IconBook",
    hugeicons: "Book01Icon",
    phosphor: "BookOpen",
    remixicon: "RiBookOpenLine",
  },
  Rss: {
    lucide: "Rss",
    tabler: "IconRss",
    hugeicons: "Rss01Icon",
    phosphor: "Rss",
    remixicon: "RiRssLine",
  },
  Bot: {
    lucide: "Bot",
    tabler: "IconRobot",
    hugeicons: "Robot01Icon",
    phosphor: "Robot",
    remixicon: "RiRobotLine",
  },
  Package: {
    lucide: "Package",
    tabler: "IconPackage",
    hugeicons: "Package01Icon",
    phosphor: "Package",
    remixicon: "RiBoxLine",
  },
  ShoppingCart: {
    lucide: "ShoppingCart",
    tabler: "IconShoppingCart",
    hugeicons: "Cart01Icon",
    phosphor: "ShoppingCart",
    remixicon: "RiShoppingCartLine",
  },
  Truck: {
    lucide: "Truck",
    tabler: "IconTruck",
    hugeicons: "Truck01Icon",
    phosphor: "Truck",
    remixicon: "RiTruckLine",
  },
  Store: {
    lucide: "Store",
    tabler: "IconBuildingStore",
    hugeicons: "Store01Icon",
    phosphor: "Storefront",
    remixicon: "RiStoreLine",
  },
  RotateCcw: {
    lucide: "RotateCcw",
    tabler: "IconRefresh",
    hugeicons: "RefreshIcon",
    phosphor: "ArrowCounterClockwise",
    remixicon: "RiRefreshLine",
  },
  FileIcon: {
    lucide: "FileIcon",
    tabler: "IconFile",
    hugeicons: "File01Icon",
    phosphor: "File",
    remixicon: "RiFileLine",
  },
  FolderIcon: {
    lucide: "FolderIcon",
    tabler: "IconFolder",
    hugeicons: "Folder01Icon",
    phosphor: "Folder",
    remixicon: "RiFolderLine",
  },
  Shapes: {
    lucide: "Shapes",
    tabler: "IconShapes",
    hugeicons: "ShapesIcon",
    phosphor: "Shapes",
    remixicon: "RiShapesLine",
  },
  Quote: {
    lucide: "Quote",
    tabler: "IconQuote",
    hugeicons: "QuoteIcon",
    phosphor: "Quotes",
    remixicon: "RiQuoteTextLine",
  },

  // Theme & time
  SunIcon: {
    lucide: "SunIcon",
    tabler: "IconSun",
    hugeicons: "Sun01Icon",
    phosphor: "Sun",
    remixicon: "RiSunLine",
  },
  MoonIcon: {
    lucide: "MoonIcon",
    tabler: "IconMoon",
    hugeicons: "Moon01Icon",
    phosphor: "Moon",
    remixicon: "RiMoonLine",
  },
  SunMediumIcon: {
    lucide: "SunMediumIcon",
    tabler: "IconSun",
    hugeicons: "Sun01Icon",
    phosphor: "Sun",
    remixicon: "RiSunLine",
  },
  CalendarIcon: {
    lucide: "CalendarIcon",
    tabler: "IconCalendar",
    hugeicons: "Calendar01Icon",
    phosphor: "Calendar",
    remixicon: "RiCalendarLine",
  },

  // Loading & misc
  Loader2Icon: {
    lucide: "Loader2Icon",
    tabler: "IconLoader",
    hugeicons: "Loading03Icon",
    phosphor: "Spinner",
    remixicon: "RiLoaderLine",
  },
  LoaderIcon: {
    lucide: "LoaderIcon",
    tabler: "IconLoader",
    hugeicons: "Loading03Icon",
    phosphor: "Spinner",
    remixicon: "RiLoaderLine",
  },
  LoaderPinwheel: {
    lucide: "LoaderPinwheel",
    tabler: "IconLoader",
    hugeicons: "Loading03Icon",
    phosphor: "Spinner",
    remixicon: "RiLoaderLine",
  },
  Bell: {
    lucide: "Bell",
    tabler: "IconBell",
    hugeicons: "Notification01Icon",
    phosphor: "Bell",
    remixicon: "RiNotificationLine",
  },
  BellIcon: {
    lucide: "BellIcon",
    tabler: "IconBell",
    hugeicons: "Notification01Icon",
    phosphor: "Bell",
    remixicon: "RiNotificationLine",
  },
  MailIcon: {
    lucide: "MailIcon",
    tabler: "IconMail",
    hugeicons: "Mail01Icon",
    phosphor: "Envelope",
    remixicon: "RiMailLine",
  },
  MessageSquare: {
    lucide: "MessageSquare",
    tabler: "IconMessageCircle",
    hugeicons: "MessageCircleIcon",
    phosphor: "ChatCircle",
    remixicon: "RiChat3Line",
  },
  ArrowLeftIcon: {
    lucide: "ArrowLeftIcon",
    tabler: "IconArrowLeft",
    hugeicons: "ArrowLeft01Icon",
    phosphor: "ArrowLeft",
    remixicon: "RiArrowLeftLine",
  },
  ArrowRightIcon: {
    lucide: "ArrowRightIcon",
    tabler: "IconArrowRight",
    hugeicons: "ArrowRight01Icon",
    phosphor: "ArrowRight",
    remixicon: "RiArrowRightLine",
  },
  CpuIcon: {
    lucide: "CpuIcon",
    tabler: "IconCpu",
    hugeicons: "CpuIcon",
    phosphor: "Cpu",
    remixicon: "RiCpuLine",
  },
  Ruler: {
    lucide: "Ruler",
    tabler: "IconRuler",
    hugeicons: "Ruler01Icon",
    phosphor: "Ruler",
    remixicon: "RiRulerLine",
  },
  Smile: {
    lucide: "Smile",
    tabler: "IconMoodSmile",
    hugeicons: "SmileIcon",
    phosphor: "Smiley",
    remixicon: "RiEmotionHappyLine",
  },
  SwatchBook: {
    lucide: "SwatchBook",
    tabler: "IconPalette",
    hugeicons: "PaletteIcon",
    phosphor: "Palette",
    remixicon: "RiPaletteLine",
  },
  Beer: {
    lucide: "Beer",
    tabler: "IconBeer",
    hugeicons: "Beer01Icon",
    phosphor: "BeerBottle",
    remixicon: "RiBeerLine",
  },
  IceCreamBowl: {
    lucide: "IceCreamBowl",
    tabler: "IconIceCream",
    hugeicons: "IceCream01Icon",
    phosphor: "IceCream",
    remixicon: "RiCakeLine",
  },
  Pizza: {
    lucide: "Pizza",
    tabler: "IconPizza",
    hugeicons: "Pizza01Icon",
    phosphor: "Pizza",
    remixicon: "RiCakeLine",
  },
  Sandwich: {
    lucide: "Sandwich",
    tabler: "IconSandwich",
    hugeicons: "Sandwich01Icon",
    phosphor: "Hamburger",
    remixicon: "RiCakeLine",
  },
  MinusIcon: {
    lucide: "MinusIcon",
    tabler: "IconMinus",
    hugeicons: "MinusSignIcon",
    phosphor: "Minus",
    remixicon: "RiSubtractLine",
  },
  BanIcon: {
    lucide: "BanIcon",
    tabler: "IconBan",
    hugeicons: "BanIcon",
    phosphor: "Prohibit",
    remixicon: "RiForbidLine",
  },
  Twitter: {
    lucide: "Twitter",
    tabler: "IconBrandTwitter",
    hugeicons: "TwitterIcon",
    phosphor: "TwitterLogo",
    remixicon: "RiTwitterXLine",
  },
  Instagram: {
    lucide: "Instagram",
    tabler: "IconBrandInstagram",
    hugeicons: "InstagramIcon",
    phosphor: "InstagramLogo",
    remixicon: "RiInstagramLine",
  },
  Twitch: {
    lucide: "Twitch",
    tabler: "IconBrandTwitch",
    hugeicons: "TwitchIcon",
    phosphor: "TwitchLogo",
    remixicon: "RiTwitchLine",
  },
};

export type IconMapKey = keyof typeof ICON_MAP;

export function getIconProps(lucideName: string) {
  const mapped = ICON_MAP[lucideName];
  if (mapped) return mapped;
  // Unmapped icons: only lucide, others omitted so IconPlaceholder falls back to Lucide
  return { lucide: lucideName };
}
