import {
  existsSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { blocks } from "../src/registry/catalog/blocks";
import { categories } from "../src/registry/catalog/categories";
import { components } from "../src/registry/catalog/components";
import { otherItems } from "../src/registry/catalog/other-items";
import {
  type BlockCatalogEntry,
  blockCatalogItemSchema,
  type CategoryCatalogEntry,
  type ComponentCatalogEntry,
  categorySchema,
  componentCatalogItemSchema,
  type RegistryFileCatalogEntry,
  type RegistryItemCatalogEntry,
  registryItemSchema,
} from "../src/registry/catalog/schema";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");
const generatedNotice =
  "// Generated by scripts/generate-registry.ts. Do not edit.\n\n";
const catalogBlocks: readonly BlockCatalogEntry[] = blocks;
const catalogCategories: readonly CategoryCatalogEntry[] = categories;
const catalogComponents: readonly ComponentCatalogEntry[] = components;
const catalogOtherItems: readonly RegistryItemCatalogEntry[] = otherItems;

type Primitive = "base" | "radix";

const fail = (message: string): never => {
  throw new Error(message);
};

const listDirectories = (path: string) =>
  readdirSync(path).filter((entry) =>
    statSync(join(path, entry)).isDirectory()
  );

const listSourceFiles = (path: string): string[] =>
  readdirSync(path).flatMap((entry) => {
    const entryPath = join(path, entry);
    if (statSync(entryPath).isDirectory()) {
      return listSourceFiles(entryPath);
    }
    return entry.endsWith(".ts") || entry.endsWith(".tsx") ? [entryPath] : [];
  });

const validateSchemas = () => {
  for (const category of catalogCategories) {
    categorySchema.parse(category);
  }
  for (const block of catalogBlocks) {
    blockCatalogItemSchema.parse(block);
  }
  for (const component of catalogComponents) {
    componentCatalogItemSchema.parse(component);
  }
  for (const item of catalogOtherItems) {
    registryItemSchema.parse(item);
  }
};

const validateUniqueNames = () => {
  const categoryNames = new Set(
    catalogCategories.map((category) => category.name)
  );
  const categoryKeys = new Set(
    catalogCategories.map((category) => category.key)
  );
  if (
    categoryNames.size !== catalogCategories.length ||
    categoryKeys.size !== catalogCategories.length
  ) {
    fail("Category keys and names must be unique");
  }
  const blockOrders = catalogCategories.flatMap((category) =>
    category.blockOrder === undefined ? [] : [category.blockOrder]
  );
  if (new Set(blockOrders).size !== blockOrders.length) {
    fail("Category blockOrder values must be unique");
  }

  const allItems = [
    ...catalogOtherItems,
    ...catalogComponents,
    ...catalogBlocks,
  ];
  const itemNames = new Set<string>();
  for (const item of allItems) {
    if (itemNames.has(item.name)) {
      fail(`Duplicate registry item name: ${item.name}`);
    }
    itemNames.add(item.name);
  }
};

const validateBlockMetadata = (
  block: BlockCatalogEntry,
  categoryNames: Set<string>
) => {
  for (const category of block.categories) {
    if (!categoryNames.has(category)) {
      fail(`Unknown category "${category}" on block ${block.name}`);
    }
  }

  const filePaths = new Set<string>(block.files.map((file) => file.path));
  if (
    !(
      filePaths.has(`${block.preview}.tsx`) ||
      filePaths.has(`${block.preview}.ts`)
    )
  ) {
    fail(
      `Preview entry ${block.preview} is not registered on block ${block.name}`
    );
  }
  if (block.previewFiles) {
    const previewFilePaths = new Set(block.previewFiles);
    if (
      previewFilePaths.size !== filePaths.size ||
      [...previewFilePaths].some((path) => !filePaths.has(path))
    ) {
      fail(
        `previewFiles must contain every registered file on block ${block.name}`
      );
    }
  }
};

const validateBlockSourceFiles = (
  block: BlockCatalogEntry,
  expectedDirectories: Record<"shared" | Primitive, Set<string>>
) => {
  const sources: readonly ("shared" | Primitive)[] =
    block.source === "shared" ? ["shared"] : ["base", "radix"];
  for (const source of sources) {
    expectedDirectories[source].add(block.name);
    const blockDirectory = join(
      root,
      "src/registry/blocks",
      source,
      block.name
    );
    const registeredFiles = new Set(
      block.files.map((file) => join(blockDirectory, file.path))
    );
    for (const file of block.files) {
      const path = join(blockDirectory, file.path);
      if (!existsSync(path)) {
        fail(`Missing source file: ${path.replace(`${root}/`, "")}`);
      }
    }
    for (const path of listSourceFiles(blockDirectory)) {
      if (!registeredFiles.has(path)) {
        fail(`Unregistered block source file: ${path.replace(`${root}/`, "")}`);
      }
    }
  }
};

const validateBlockSources = () => {
  const categoryNames = new Set(
    catalogCategories.map((category) => category.name)
  );
  const expectedDirectories = {
    shared: new Set<string>(),
    base: new Set<string>(),
    radix: new Set<string>(),
  };
  for (const block of catalogBlocks) {
    validateBlockMetadata(block, categoryNames);
    validateBlockSourceFiles(block, expectedDirectories);
  }
  return expectedDirectories;
};

const validateBlockDirectories = (
  expectedBlockDirectories: Record<"shared" | Primitive, Set<string>>
) => {
  for (const source of ["shared", "base", "radix"] as const) {
    const directory = join(root, "src/registry/blocks", source);
    const actual = new Set(listDirectories(directory));
    const expected = expectedBlockDirectories[source];
    const unregistered = [...actual].filter((name) => !expected.has(name));
    const missing = [...expected].filter((name) => !actual.has(name));
    if (unregistered.length || missing.length) {
      fail(
        `${source} block directory mismatch. Unregistered: ${unregistered.join(", ") || "none"}. Missing: ${missing.join(", ") || "none"}.`
      );
    }
  }
};

const validateNonBlockFiles = () => {
  for (const item of [...catalogComponents, ...catalogOtherItems]) {
    for (const file of item.files) {
      if (!existsSync(join(root, file.path))) {
        fail(`Missing source file: ${file.path}`);
      }
    }
  }
};

const getRegistryDependencyName = (dependency: string) => {
  if (!dependency.startsWith("https://")) {
    return dependency;
  }
  const fileName = dependency.split("/").at(-1);
  return fileName?.endsWith(".json")
    ? fileName.slice(0, -5)
    : (fileName ?? dependency);
};

const validateDependencies = () => {
  const packageJson = JSON.parse(
    readFileSync(join(root, "package.json"), "utf8")
  ) as {
    dependencies: Record<string, string>;
    devDependencies: Record<string, string>;
  };
  const packages = new Set([
    ...Object.keys(packageJson.dependencies),
    ...Object.keys(packageJson.devDependencies),
  ]);
  const registryItems = new Set([
    ...catalogComponents.map((item) => item.name),
    ...catalogOtherItems.map((item) => item.name),
    ...readdirSync(join(root, "src/registry/ui"))
      .filter((file) => file.endsWith(".tsx"))
      .map((file) => file.slice(0, -4)),
    ...readdirSync(join(root, "src/registry/bases/base/ui"))
      .filter((file) => file.endsWith(".tsx"))
      .map((file) => file.slice(0, -4)),
  ]);

  for (const item of [
    ...catalogBlocks,
    ...catalogComponents,
    ...catalogOtherItems,
  ]) {
    for (const dependency of item.dependencies ?? []) {
      if (!packages.has(dependency)) {
        fail(`Unknown package dependency "${dependency}" on ${item.name}`);
      }
    }
    for (const dependency of item.registryDependencies ?? []) {
      if (!registryItems.has(getRegistryDependencyName(dependency))) {
        fail(`Unknown registry dependency "${dependency}" on ${item.name}`);
      }
    }
  }
};

const validateCatalog = () => {
  validateSchemas();
  validateUniqueNames();
  validateBlockDirectories(validateBlockSources());
  validateNonBlockFiles();
  validateDependencies();
};

const buildBlockFiles = (
  block: BlockCatalogEntry,
  primitive: Primitive
): RegistryFileCatalogEntry[] => {
  const source = block.source === "shared" ? "shared" : primitive;
  return block.files.map((file) => ({
    ...file,
    path: `src/registry/blocks/${source}/${block.name}/${file.path}`,
  }));
};

const buildBlockItem = (block: BlockCatalogEntry, primitive: Primitive) => {
  const {
    name,
    title,
    description,
    dependencies,
    registryDependencies,
    files: _files,
    categories: _categories,
    source: _source,
    preview: _preview,
    previewFiles: _previewFiles,
    layout: _layout,
    ...extra
  } = block;

  return {
    name,
    type: "registry:block",
    title,
    description,
    ...(dependencies ? { dependencies: [...dependencies] } : {}),
    ...(registryDependencies
      ? { registryDependencies: [...registryDependencies] }
      : {}),
    files: buildBlockFiles(block, primitive),
    ...extra,
  };
};

const buildComponentItem = (item: ComponentCatalogEntry) => {
  const { site: _site, ...registryItem } = item;
  return registryItem;
};

const buildRegistry = (primitive: Primitive) => {
  const uiItems = catalogOtherItems.filter(
    (item) => item.type === "registry:ui"
  );
  const remainingItems = catalogOtherItems.filter(
    (item) => item.type !== "registry:ui"
  );
  const items = [
    ...uiItems,
    ...catalogComponents.map(buildComponentItem),
    ...remainingItems,
    ...catalogBlocks.map((block) => buildBlockItem(block, primitive)),
  ];
  for (const item of items) {
    registryItemSchema.parse(item);
  }

  return {
    $schema: "https://ui.shadcn.com/schema/registry.json",
    name: "Shadcn UI Blocks",
    homepage: "https://www.shadcnui-blocks.com",
    items,
  };
};

const renderFiles = (files: readonly string[]) =>
  `[${files.map((path) => `{ path: ${JSON.stringify(path)} }`).join(", ")}]`;

const renderLayout = (layout: BlockCatalogEntry["layout"]) => {
  switch (layout) {
    case "navbar":
      return "NavbarLayout";
    case "footer":
      return "FooterLayout";
    case "full-height":
      return "FullHeightLayout";
    default:
      return undefined;
  }
};

const renderPreviewBlock = (block: BlockCatalogEntry) => {
  const categoryReferences = block.categories
    .map((category) => {
      const match = catalogCategories.find((entry) => entry.name === category);
      return `categories.${match?.key ?? fail(`Unknown category ${category}`)}`;
    })
    .join(", ");
  const previewFiles =
    block.previewFiles ?? block.files.map((file) => file.path);
  const layout = renderLayout(block.layout);
  const lines = [
    "  {",
    `    name: ${JSON.stringify(block.name)},`,
    `    title: ${JSON.stringify(block.title)},`,
    `    description: ${JSON.stringify(block.description)},`,
  ];

  if (block.source === "shared") {
    lines.push(
      `    component: React.lazy(() => import(${JSON.stringify(`@/registry/blocks/shared/${block.name}/${block.preview}`)})),`,
      `    files: ${renderFiles(previewFiles)},`
    );
  } else {
    lines.push(
      "    primitives: {",
      "      radix: {",
      `        component: React.lazy(() => import(${JSON.stringify(`@/registry/blocks/radix/${block.name}/${block.preview}`)})),`,
      `        files: ${renderFiles(previewFiles)},`,
      "      },",
      "      base: {",
      `        component: React.lazy(() => import(${JSON.stringify(`@/registry/blocks/base/${block.name}/${block.preview}`)})),`,
      `        files: ${renderFiles(previewFiles)},`,
      "      },",
      "    },"
    );
  }

  lines.push(`    categories: [${categoryReferences}],`);
  if (layout) {
    lines.push(`    layout: ${layout},`);
  }
  lines.push("  },");
  return lines.join("\n");
};

const renderPreviewRegistry = () => {
  const categoryObject = Object.fromEntries(
    catalogCategories.map(({ key, name, title }) => [key, { name, title }])
  );
  const categoryOrder = new Map(
    catalogCategories.map((category) => [
      category.name,
      category.blockOrder ?? Number.POSITIVE_INFINITY,
    ])
  );
  const orderedBlocks = [...catalogBlocks].sort((a, b) => {
    const orderDifference =
      (categoryOrder.get(a.categories[0]) ?? Number.POSITIVE_INFINITY) -
      (categoryOrder.get(b.categories[0]) ?? Number.POSITIVE_INFINITY);
    return (
      orderDifference ||
      a.name.localeCompare(b.name, undefined, { numeric: true })
    );
  });

  return `${generatedNotice}import React, { type JSX } from "react";
import { NavbarLayout } from "./block-layouts";

export interface BlockCategory {
  name: string;
  title: string;
}

export interface BlockPrimitiveVariant {
  component: React.LazyExoticComponent<() => JSX.Element | Promise<JSX.Element>>;
  files: { path: string }[];
}

export interface RegistryBlock {
  name: string;
  title: string;
  description: string;
  categories: BlockCategory[];
  component?: React.LazyExoticComponent<() => JSX.Element | Promise<JSX.Element>>;
  files?: { path: string }[];
  primitives?: { radix: BlockPrimitiveVariant; base: BlockPrimitiveVariant };
  layout?: React.FC<{ children: React.ReactNode }>;
}

export const categories = ${JSON.stringify(categoryObject, null, 2)} as const;

const FooterLayout = ({ children }: { children: React.ReactNode }) => (
  <div className="relative flex size-full min-h-screen flex-col">
    <div className="grow bg-muted/50" />
    {children}
  </div>
);

const FullHeightLayout = ({ children }: { children: React.ReactNode }) => (
  <div className="min-h-screen">{children}</div>
);

export const blocks: RegistryBlock[] = [
${orderedBlocks.map(renderPreviewBlock).join("\n")}
];
`;
};

const renderCustomizedComponents = () => {
  const groups: Record<string, Record<string, unknown>[]> = {};
  for (const component of catalogComponents) {
    if (!component.site) {
      continue;
    }
    const { group, title, ...metadata } = component.site;
    groups[group] ??= [];
    groups[group].push({
      title,
      type: group,
      name: component.name,
      ...metadata,
    });
  }
  return `${generatedNotice}export const customizedComponents = ${JSON.stringify(groups, null, 2)} as const;\n`;
};

const outputs = new Map<string, string>([
  ["registry.json", `${JSON.stringify(buildRegistry("radix"), null, 2)}\n`],
  [
    "registry-radix.json",
    `${JSON.stringify(buildRegistry("radix"), null, 2)}\n`,
  ],
  ["registry-base.json", `${JSON.stringify(buildRegistry("base"), null, 2)}\n`],
  ["src/config/registry/index.tsx", renderPreviewRegistry()],
  ["src/description/customized-components.ts", renderCustomizedComponents()],
]);

validateCatalog();

const changed: string[] = [];
for (const [path, content] of outputs) {
  const absolutePath = join(root, path);
  if (
    !existsSync(absolutePath) ||
    readFileSync(absolutePath, "utf8") !== content
  ) {
    changed.push(path);
    if (!checkOnly) {
      writeFileSync(absolutePath, content);
    }
  }
}

if (checkOnly && changed.length) {
  fail(
    `Generated registry files are stale:\n${changed.map((path) => `- ${path}`).join("\n")}`
  );
}

if (!checkOnly) {
  console.log(`Generated ${outputs.size} registry files.`);
}
